matrix:
    include:
        - os: linux
          dist: xenial
          language: c
          env:
              - NAME="Test"

        - os: linux
          dist: xenial
          language: c
          env:
              - NAME="ValgrindTest"

script:
    - Tools/travis_ci.sh

before_install:
    - Tools/travis_before_install.sh
